### ISSUE TITLE
갱신 안 됨

### ISSUE THREAD

**Issue by lens0021** [femiwiki/rankingbot#11]
5월 25일 이후 갱신이 안 되고 있습니다.

* ["페미위키:활동적인 사용자"의 편집 역사](https://femiwiki.com/index.php?title=%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%ED%99%9C%EB%8F%99%EC%A0%81%EC%9D%B8_%EC%82%AC%EC%9A%A9%EC%9E%90&action=history)
```bash
$ docker exec $(docker container ls -qf 'name=bots_ranking-bot') cat /tmp/log | tail -20
WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes.
WARNING:mwclient.client:Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.
WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes.
WARNING:mwclient.client:Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.
WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes.
WARNING:mwclient.client:Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.
WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes.
WARNING:mwclient.client:Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/rankingbot/__main__.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/rankingbot/main.py", line 64, in main
    for i, (score, user) in zip(range(TOP_N), scores_to_show):
  File "/usr/local/lib/python3.7/site-packages/rankingbot/main.py", line 45, in <genexpr>
    if int(user) not in blocked_users and not re.match(
ValueError: invalid literal for int() with base 10: ''
```

**Comment by lens0021** [comment]
랭킹봇이 최근 바뀜을 읽어올 때 사용자 아이디(정수)를 당연히 있을 것으로 가정하고 처리하는데, 현재 페미위키:운영일지 문서의 일부 판을 수정한 사용자가 판 숨김 처리되어 불러와지지 않았으며 이에 따라 발생한 오류입니다.

![image](https://user-images.githubusercontent.com/28209361/58608835-50b78380-82e0-11e9-9430-a8443d4d79db.png)

일단 숨김 처리에서 이름을 제외시키고 봇을 다시 실행하고, 예외 처리는 추가하는 것으로 하면 되겠습니다.

**Comment by lens0021** [comment]
판 숨기기 설정 변경했습니다([기록](https://femiwiki.com/index.php?title=%ED%8A%B9%EC%88%98:%EA%B8%B0%EB%A1%9D&page=%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4%3A%EC%9A%B4%EC%98%81%EC%9D%BC%EC%A7%80%2F2019-05-25))

**Comment by lens0021** [comment]
파이썬을 사랑하는 @love-adela 님께 살포시 멘션 넣어봅니다
